services:
  # Full-stack deployment (Backend serves Frontend + API)
  - type: web
    name: trend-compass-ai
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && npm ci && npm run build
    startCommand: python wsgi_runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: NODE_VERSION
        value: 18
