services:
  - type: web
    name: trend-compass-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi_runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
