services:
  # Backend API
  - type: web
    name: trend-compass-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi_runner.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11

  # Frontend Static Site
  - type: web
    name: trend-compass-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18
