services:
  - type: web
    name: trend-compass
    env: python
    buildCommand: |
      npm install
      npm run build
      cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: QLOO_API_KEY
        sync: false
      - key: QLOO_API_URL
        value: https://hackathon.api.qloo.com
